---
- name: Reload Service | mariadb
  service:
    state: reloaded
    name: mysql
  tags:
    - disruptive

- name: Stop Service | mariadb
  service:
    name: mysql
    state: stopped

- name: Start Service | mariadb
  service:
    name: mysql
    state: started